apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: npm
spec:
  workspaces:
    - name: source

  steps:
    - name: npm-install
      image: node:20
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing npm dependencies..."
        npm install

---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: Jasmine
spec:
  workspaces:
    - name: source

  steps:
    - name: jasmine-test
      image: node:20
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Running Jasmine tests..."
        npm install
        npx jasmine